export const STORE_RESTAURANT_DATA = 'STORE_RESTAURANT_DATA'
export const TOGGLE_CURRENT_PAGE = 'TOGGLE_CURRENT_PAGE'
export const SELECT_CURRENT_GENRE = 'SELECT_CURRENT_GENRE'
export const SEARCH_RESTAURANT_DATA = 'SEARCH_RESTAURANT_DATA'